def BoMCountEmail():
    try:
        from datetime import datetime, timedelta

        # Current datetime
        now = datetime.now()

        # Calculate today_start, yesterday_start, and today_end
        today_start = now.replace(hour=7, minute=30, second=0, microsecond=0)
        yesterday_start = today_start - timedelta(days=1)
        today_end = today_start - timedelta(seconds=1) + timedelta(days=1)

        # Format datetime objects to the desired format
        fromDate = yesterday_start.strftime('%Y-%m-%d %H:%M:%S')
        toDate = today_start.strftime('%Y-%m-%d %H:%M:%S')

        try:
            queryEmail = 'select EmailID from MESPRODDB.dbo.MST_EmailUsers where Priority=1 and IsActive=1 and IsDeleted=0'
            emails = system.db.runQuery(queryEmail)  # Run the query directly to get the list of emails

            # Collect all email addresses into a list
            email_list = [email[0] for email in emails]  # Assuming emails is a list of tuples
        except Exception as e:
            system.util.getLogger("BomCountMail").error("Error fetching emails " + str(e))
            return

        # If there are no email addresses, log and exit
        if not email_list:
            system.util.getLogger("BomCountMail").error("No Email present " + str(e))
            return

        # Other details
        line = "Legacy Axle"
        area = "Legacy Axle Main Line"
        station = 'LAQG02'
        workstationID = 331



        query_path = "Project_VECV/RaCodeCount/getData"  # Replace with the actual Named Query path
        params = {
            "Workstation": station,
            "ToDate": toDate,
            "FromDate": fromDate
        }


        results = system.db.runNamedQuery(query_path, params)


        # Correct way to handle PyDataset: Use getRowCount() and getColumnNames() methods
        row_count = results.getRowCount()
        column_names = results.getColumnNames()

        # Construct HTML table without row coloring
        html = """
        <style>
            table {
                width: 100%;
                border-collapse: collapse;
                font-family: Arial, sans-serif;
            }
            th, td {
                padding: 8px;
                text-align: left;
                border: 1px solid #ddd;
            }
            th {
                background-color: #0096FF;
                color: white;
            }
            tr:nth-child(even) {
                background-color: #f2f2f2;
            }
            tr:hover {
                background-color: #ddd;
                transition: background-color 0.3s ease;
            }
            td {
                color: #333;
            }
        </style>
        <table>
            <thead>
                <tr>
                    <th>BoM</th>
                    <th>Production Count</th>
                </tr>
            </thead>
            <tbody>
        """

        # Add rows to the table
        for row_idx in range(row_count):
            bom = results.getValueAt(row_idx, 'RACode')  # Assuming the column is 'BoM'
            count = results.getValueAt(row_idx, 'Count')
            html += "<tr><td>" + str(bom) + "</td><td>" + str(count) + "</td></tr>"

        html += "</tbody></table>"

        # Prepare email subject and body
        subject = "MES || AXLE SHOP || Daily BoM Tracker Report (" + fromDate + " All Shifts)"
        body = (
            "<p>Dear All,</p>"
            "<p>Please Find Attached <B>AXLE Daily BoM Tracker Report</B> for date " + fromDate + " All Shifts</p>"
            + html +
            "<p style='background-color: #D3D3D3 ; font-size: small;'><B>Click <a href='http://10.109.1.71:8088/data/perspective/client/VECV_Ignition_V1_1_1/RaCodeCountProductionReport'><u>HERE</u></a> to view this report in MES PLATFORM</B></p>"
            "<p style='background-color: #D3D3D3 ; font-size: small;'><B>Click <a href='https://isupport.vecv.net/MDLServiceMgmt/SR_LogServiceCatalog.aspx?es=IfFNluw5HyCtQkeT7wQi8eZB4Ve2VK1WrmItHTyquJCWYFOue%2bscW7q4hr8fsypB0j410plSUDEj4%2bnn%2bnV82Cwl63oy%2f0Ek38ThogbDjo81XZ1pfJKCh8vzszs8hYT1U7o58v6t7ZCerta3PXRaCg%3d%3d'><u>HERE</u></a> to Raise request for user ID creation in MES to view all reports</B></p>"
            "<p style='background-color: yellow; font-size: small;'><B>This is autogenerated mail please do not reply.</B></p>"
            "<p style='background-color: yellow; font-size: small;'><B>For any support contact Aniket Sagar on <a href='mailto:asgar3@vecv.in'>asgar3@vecv.in</a> or 7903511741.</B></p>"
            "<p style='font-style: italic; '><B></I>Regards,<br>MES ADMIN</I></B></p>"
        )

        # Send email to the list of email addresses
        try:
            system.net.sendEmail(
                smtpProfile="SMTPEmail", 
                fromAddr="mes_email_admin@vecv.in", 
                subject=subject, 
                body=body, 
                html=1, 
                to=email_list  # Send to the list of emails
            )
            # Log successful email sending
            system.util.getLogger("HPRMail-->send email to all users")
        except Exception as e:
            system.util.getLogger("BoMMail").error("Failed to send email " + str(e))

    except Exception as e:
        system.util.getLogger("BomCountMail").error("Failed to send email " + str(e))