Select M.ModelName,V.SEALENT_PROGRAM_ID380738_TM567,V.SEALENT_PROGRAM_ID400105_TM530,V.SEALENT_PROGRAM_ID347009_TM333,
V.SEALENT_PROGRAM_ID347003_TM340,V.SEALENT_PROGRAM_ID347003_TM341,V.SEALENT_PROGRAM_ID347578_TM551,V.SEALENT_PROGRAM_ID355737_TM552,
V.SEALENT_PROGRAM_SELECTION_8,V.SEALENT_PROGRAM_SELECTION_9,V.SEALENT_PROGRAM_SELECTION_10,V.SEALENT_PROGRAM_SELECTION_11,
V.SEALENT_PROGRAM_SELECTION_12,V.SEALENT_PROGRAM_SELECTION_13,V.SEALENT_PROGRAM_SELECTION_14,V.SEALENT_PROGRAM_SELECTION_15,
V.SEALENT_PROGRAM_SELECTION_16,V.SEALENT_PROGRAM_SELECTION_17,V.SEALENT_PROGRAM_SELECTION_18,V.SEALENT_PROGRAM_SELECTION_19,
V.SEALENT_PROGRAM_SELECTION_20,V.SEALENT_PROGRAM_SELECTION_21,V.SEALENT_PROGRAM_SELECTION_22,V.SEALENT_PROGRAM_SELECTION_23,
V.SEALENT_PROGRAM_SELECTION_24
from MST_VerticalSeleantBit V
inner join M_BOM B on B.M_BOM_Id=V.M_BOM_Id
inner join MST_Model M on M.MST_Model_Id=V.MST_Model_Id
where V.MST_Area_Id=  :MST_Area_Id   and V.MST_Line_id= :MST_Line_id   and B.M_BOMNumber=  :M_BOMNumber  and V.IsActive=1 and V.IsDeleted=0
and V.MST_WorkStation_Id=  :MST_WorkStation_Id 