Select M.ModelName,V.POKAYOKE_OIL,V.POKAYOKE_LOCKTITE,V.POKAYOKE_NRB,V.POKAYOKE_SYNCHRO,V.POKAYOKE_CIRCLIP_ID200380
,V.POKAYOKE_CIRCLIP_ID205389,V.POKAYOKE_CIRCLIP_ID325347,V.POKAYOKE_CIRCLIP_ID602932,V.POKAYOKE_CIRCLIP_ME580789
,V.POKAYOKE_CIRCLIP_ME600195,V.POKAYOKE_WASHER_FOLD,V.POKAYOKE_SPLIT_PIN,V.POKAYOKE_GAUGE,V.POKAYOKE_SLEEVE
,V.POKAYOKE_CRIMPING,V.POKAYOKE_BEARING
from MST_MainShaft02 V
inner join M_BOM B on B.M_BOM_Id=V.M_BOM_Id
inner join MST_Model M on M.MST_Model_Id=V.MST_Model_Id
where V.MST_Area_Id= :MST_Area_Id  and V.MST_Line_id= :MST_Line_id and B.M_BOMNumber= :M_BOMNumber and V.IsActive=1 and V.IsDeleted=0 
and V.MST_WorkStation_Id= :MST_WorkStation_Id