SELECT [Variant Type]
,[Test_startDate]
,[Test_endDate]
,[Total Test Time]
,[Oil Filling Status]
,[Oil Drain Status]
,[Input RPM]
,[Torque]
,[Torque Status]
,[Diff LH] as 'Break LH'
,[Diff RH] as 'Break RH'
,[Gear Ratio]
,[Gear Ratio Status]
,[Noise]
,[Noise Status]
,[Vibration 1]
,[Vibration 2]
,[Vibration 3]
,[Vibration Status]
,[Delta Spin]
,[Delta Spin Status]
,[Final Result]
FROM [Test Data]
where [Part Serial No] =  :SerialNumber 