Select M.ModelName,V.ET_35S6_TILTER_POSITION_SELECTION_1180,V.ET_35S6_TILTER_POSITION_SELECTION_1295,V.ET_40S5_TILTER_POSITION_SELECTION_2109_357,
V.ET_40S5_TILTER_POSITION_SELECTION_2,V.ET_40S6_TILTER_POSITION_SELECTION_2109_357,V.ET_40S6_TILTER_POSITION_SELECTION_2,
V.ET_50S7_TILTER_POSITION_SELECTION_1411,V.ET_50S7_TILTER_POSITION_SELECTION_1380,V.ET_60S6_TILTER_POSITION_SELECTION_1380,
V.ET_60S6_TILTER_POSITION_SELECTION_2,V.ET_60S7_TILTER_POSITION_SELECTION_1380,V.ET_60S7_TILTER_POSITION_SELECTION_2
from MST_VerticalServoBit V
inner join M_BOM B on B.M_BOM_Id=V.M_BOM_Id
inner join MST_Model M on M.MST_Model_Id=V.MST_Model_Id
where V.MST_Area_Id= :MST_Area_Id and V.MST_Line_id= :MST_Line_id and B.M_BOMNumber= :M_BOMNumber and V.IsActive=1 and V.IsDeleted=0
and V.MST_WorkStation_Id=  :MST_WorkStation_Id