exec usp_AddUpdateTRN_ErrorPrrofQG
@Id = :Id,
@Area= :Area ,
@Line= :Line ,
@WorkStation= :WorkStation ,
@BOM= :BOM ,
@Part= :Part ,
@Description = :Description,
@CreatedBy= :CreatedBy,
@Active= :Active,
@ALTERNATEPART = :ALTERNATEPART,
