Select M.ModelName,V.SERVO_PROGRAM_SELECTION_ET60S7,V.SERVO_PROGRAM_SELECTION_ET50S7,V.SERVO_PROGRAM_SELECTION_ET40S6,
V.SERVO_PROGRAM_SELECTION_ET40S5,V.SERVO_PROGRAM_SELECTION_5,V.SERVO_PROGRAM_SELECTION_6,V.SERVO_PROGRAM_SELECTION_ET60S6,
V.SERVO_PROGRAM_SELECTION_ET35S6
from MST_NewNumberPunching V
inner join M_BOM B on B.M_BOM_Id=V.M_BOM_Id
inner join MST_Model M on M.MST_Model_Id=V.MST_Model_Id
where V.MST_Area_Id= :MST_Area_Id  and V.MST_Line_id= :MST_Line_id  and B.M_BOMNumber= :M_BOMNumber  and V.IsActive=1 and V.IsDeleted=0
and V.MST_WorkStation_Id= :MST_WorkStation_Id 
