Select M.ModelName,V.LEAK_TEST_PROGRAM_SELECTION_1,V.LEAK_TEST_PROGRAM_SELECTION_2,V.LEAK_TEST_PROGRAM_SELECTION_3,V.LEAK_TEST_PROGRAM_SELECTION_4,
V.LEAK_TEST_PROGRAM_SELECTION_5,V.LEAK_TEST_PROGRAM_SELECTION_6,V.LEAK_TEST_PROGRAM_SELECTION_7,V.LEAK_TEST_PROGRAM_SELECTION_8,
V.LEAK_TEST_PROGRAM_SELECTION_9,V.LEAK_TEST_PROGRAM_SELECTION_10,V.LEAK_TEST_PROGRAM_SELECTION_11,V.LEAK_TEST_PROGRAM_SELECTION_12
,V.LEAK_TEST_PROGRAM_SELECTION_13,V.LEAK_TEST_PROGRAM_SELECTION_14,V.LEAK_TEST_PROGRAM_SELECTION_15,V.LEAK_TEST_PROGRAM_SELECTION_16,
V.LEAK_TEST_PROGRAM_SELECTION_17,V.LEAK_TEST_PROGRAM_SELECTION_18,V.LEAK_TEST_PROGRAM_SELECTION_19,V.LEAK_TEST_PROGRAM_SELECTION_20,
V.LEAK_TEST_PROGRAM_SELECTION_21,V.LEAK_TEST_PROGRAM_SELECTION_22,V.LEAK_TEST_PROGRAM_SELECTION_23,V.LEAK_TEST_PROGRAM_SELECTION_24
from MST_LeakTestBit V
inner join M_BOM B on B.M_BOM_Id=V.M_BOM_Id
inner join MST_Model M on M.MST_Model_Id=V.MST_Model_Id
where V.MST_Area_Id= :MST_Area_Id  and V.MST_Line_id= :MST_Line_id  and B.M_BOMNumber=  :M_BOMNumber and V.IsActive=1 and V.IsDeleted=0
and V.MST_WorkStation_Id=  :MST_WorkStation_Id