Select M.ModelName,V.POKAYOKE_OIL,V.POKAYOKE_LOCKTITE,V.POKAYOKE_NRB,V.POKAYOKE_SYNCHRO,V.POKAYOKE_CIRCLIP_1,
V.POKAYOKE_CIRCLIP_2,V.POKAYOKE_CIRCLIP_3,V.POKAYOKE_CIRCLIP_4,V.POKAYOKE_WASHER_FOLD,V.POKAYOKE_SPLIT_PIN,
V.POKAYOKE_GAUGE,V.POKAYOKE_SLEEVE,V.POKAYOKE_CRIMPING,V.POKAYOKE_BEARING,V.MAIN_SHAFT_TORQUE_250_KGFM,
V.MAIN_SHAFT_TORQUE_300_KGFM, V.MAIN_SHAFT_TORQUE_325_KGFM,V.NO_TORQUE_REQUIRED
from MST_ShaftDCNRBit V
inner join M_BOM B on B.M_BOM_Id=V.M_BOM_Id
inner join MST_Model M on M.MST_Model_Id=V.MST_Model_Id
where V.MST_Area_Id= :MST_Area_Id and V.MST_Line_id= :MST_Line_id and B.M_BOMNumber= :M_BOMNumber and V.IsActive=1 and V.IsDeleted=0 
and V.MST_WorkStation_Id= :MST_WorkStation_Id